# This is a basic workflow that is manually triggered

name: Compile test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [pull_request]

jobs:
  build:
    name: Compile test
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd Code/Java
        javac * -d ../../Compile
        
  run-failed:
    name: Close Pull
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()
    steps:
    - name: removing
      uses: peter-evans/close-pull@v1
      with:
        pull-request-number: 1
        comment: Auto-closing pull request
        delete-branch: true
  automerge:
    runs-on: ubuntu-latest
    needs: [build]
    if: success()
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
