# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

jobs:
  build:
    name: Compile test
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd Code/Java
        javac * -d ../../Compile
